"""
Base de datos de acciones populares para autocompletado.
Incluye las empresas más buscadas del S&P 500, NASDAQ y otras populares.
"""

# Formato: "TICKER": "Nombre de la Empresa"
POPULAR_STOCKS = {
    # === MEGA CAPS (Top 50) ===
    "AAPL": "Apple Inc.",
    "MSFT": "Microsoft Corporation",
    "GOOGL": "Alphabet Inc. (Google) Class A",
    "GOOG": "Alphabet Inc. (Google) Class C",
    "AMZN": "Amazon.com Inc.",
    "NVDA": "NVIDIA Corporation",
    "META": "Meta Platforms Inc. (Facebook)",
    "TSLA": "Tesla Inc.",
    "BRK-B": "Berkshire Hathaway Inc. Class B",
    "BRK-A": "Berkshire Hathaway Inc. Class A",
    "JPM": "JPMorgan Chase & Co.",
    "JNJ": "Johnson & Johnson",
    "V": "Visa Inc.",
    "UNH": "UnitedHealth Group Inc.",
    "XOM": "Exxon Mobil Corporation",
    "PG": "Procter & Gamble Co.",
    "MA": "Mastercard Inc.",
    "HD": "The Home Depot Inc.",
    "CVX": "Chevron Corporation",
    "LLY": "Eli Lilly and Company",
    "MRK": "Merck & Co. Inc.",
    "ABBV": "AbbVie Inc.",
    "PEP": "PepsiCo Inc.",
    "KO": "The Coca-Cola Company",
    "AVGO": "Broadcom Inc.",
    "COST": "Costco Wholesale Corporation",
    "TMO": "Thermo Fisher Scientific Inc.",
    "MCD": "McDonald's Corporation",
    "WMT": "Walmart Inc.",
    "CSCO": "Cisco Systems Inc.",
    "ACN": "Accenture plc",
    "ABT": "Abbott Laboratories",
    "DHR": "Danaher Corporation",
    "ADBE": "Adobe Inc.",
    "CRM": "Salesforce Inc.",
    "NKE": "Nike Inc.",
    "PFE": "Pfizer Inc.",
    "NFLX": "Netflix Inc.",
    "ORCL": "Oracle Corporation",
    "AMD": "Advanced Micro Devices Inc.",
    "INTC": "Intel Corporation",
    "DIS": "The Walt Disney Company",
    "VZ": "Verizon Communications Inc.",
    "T": "AT&T Inc.",
    "CMCSA": "Comcast Corporation",
    "WFC": "Wells Fargo & Company",
    "BAC": "Bank of America Corporation",
    "PM": "Philip Morris International Inc.",
    "RTX": "RTX Corporation (Raytheon)",
    "NEE": "NextEra Energy Inc.",
    
    # === TECNOLOGÍA ===
    "IBM": "International Business Machines",
    "QCOM": "Qualcomm Inc.",
    "TXN": "Texas Instruments Inc.",
    "INTU": "Intuit Inc.",
    "NOW": "ServiceNow Inc.",
    "AMAT": "Applied Materials Inc.",
    "LRCX": "Lam Research Corporation",
    "MU": "Micron Technology Inc.",
    "ADI": "Analog Devices Inc.",
    "KLAC": "KLA Corporation",
    "SNPS": "Synopsys Inc.",
    "CDNS": "Cadence Design Systems",
    "PANW": "Palo Alto Networks Inc.",
    "CRWD": "CrowdStrike Holdings Inc.",
    "SNOW": "Snowflake Inc.",
    "DDOG": "Datadog Inc.",
    "ZS": "Zscaler Inc.",
    "NET": "Cloudflare Inc.",
    "PLTR": "Palantir Technologies Inc.",
    "COIN": "Coinbase Global Inc.",
    "SQ": "Block Inc. (Square)",
    "PYPL": "PayPal Holdings Inc.",
    "SHOP": "Shopify Inc.",
    "UBER": "Uber Technologies Inc.",
    "LYFT": "Lyft Inc.",
    "ABNB": "Airbnb Inc.",
    "ROKU": "Roku Inc.",
    "SPOT": "Spotify Technology S.A.",
    "DOCU": "DocuSign Inc.",
    "ZM": "Zoom Video Communications",
    "TWLO": "Twilio Inc.",
    "OKTA": "Okta Inc.",
    "TEAM": "Atlassian Corporation",
    "WDAY": "Workday Inc.",
    "SPLK": "Splunk Inc.",
    "VEEV": "Veeva Systems Inc.",
    "ANSS": "ANSYS Inc.",
    "FTNT": "Fortinet Inc.",
    "MRVL": "Marvell Technology Inc.",
    "ON": "ON Semiconductor Corporation",
    "NXPI": "NXP Semiconductors N.V.",
    "SWKS": "Skyworks Solutions Inc.",
    "MPWR": "Monolithic Power Systems",
    "MCHP": "Microchip Technology Inc.",
    "HPE": "Hewlett Packard Enterprise",
    "HPQ": "HP Inc.",
    "DELL": "Dell Technologies Inc.",
    
    # === FINANZAS ===
    "GS": "Goldman Sachs Group Inc.",
    "MS": "Morgan Stanley",
    "C": "Citigroup Inc.",
    "AXP": "American Express Company",
    "SCHW": "Charles Schwab Corporation",
    "BLK": "BlackRock Inc.",
    "SPGI": "S&P Global Inc.",
    "CB": "Chubb Limited",
    "MMC": "Marsh & McLennan Companies",
    "PGR": "Progressive Corporation",
    "AON": "Aon plc",
    "TFC": "Truist Financial Corporation",
    "USB": "U.S. Bancorp",
    "PNC": "PNC Financial Services",
    "COF": "Capital One Financial",
    "BK": "Bank of New York Mellon",
    "AIG": "American International Group",
    "MET": "MetLife Inc.",
    "PRU": "Prudential Financial Inc.",
    "AFL": "Aflac Inc.",
    "TRV": "The Travelers Companies",
    "ALL": "The Allstate Corporation",
    "ICE": "Intercontinental Exchange",
    "CME": "CME Group Inc.",
    "MCO": "Moody's Corporation",
    "MSCI": "MSCI Inc.",
    "FIS": "Fidelity National Information",
    "FISV": "Fiserv Inc.",
    "ADP": "Automatic Data Processing",
    "PAYX": "Paychex Inc.",
    
    # === HEALTHCARE / PHARMA ===
    "BMY": "Bristol-Myers Squibb Company",
    "AMGN": "Amgen Inc.",
    "GILD": "Gilead Sciences Inc.",
    "REGN": "Regeneron Pharmaceuticals",
    "VRTX": "Vertex Pharmaceuticals Inc.",
    "BIIB": "Biogen Inc.",
    "MRNA": "Moderna Inc.",
    "ZTS": "Zoetis Inc.",
    "SYK": "Stryker Corporation",
    "BSX": "Boston Scientific Corporation",
    "MDT": "Medtronic plc",
    "ISRG": "Intuitive Surgical Inc.",
    "EW": "Edwards Lifesciences Corp.",
    "DXCM": "DexCom Inc.",
    "IDXX": "IDEXX Laboratories Inc.",
    "IQV": "IQVIA Holdings Inc.",
    "A": "Agilent Technologies Inc.",
    "BDX": "Becton Dickinson and Company",
    "BAX": "Baxter International Inc.",
    "CI": "The Cigna Group",
    "ELV": "Elevance Health Inc.",
    "HUM": "Humana Inc.",
    "CNC": "Centene Corporation",
    "CVS": "CVS Health Corporation",
    "WBA": "Walgreens Boots Alliance",
    "MCK": "McKesson Corporation",
    "CAH": "Cardinal Health Inc.",
    "ABC": "AmerisourceBergen Corp.",
    
    # === CONSUMO ===
    "SBUX": "Starbucks Corporation",
    "CMG": "Chipotle Mexican Grill",
    "YUM": "Yum! Brands Inc.",
    "DPZ": "Domino's Pizza Inc.",
    "DARDEN": "Darden Restaurants Inc.",
    "LOW": "Lowe's Companies Inc.",
    "TJX": "The TJX Companies Inc.",
    "ROST": "Ross Stores Inc.",
    "TGT": "Target Corporation",
    "DG": "Dollar General Corporation",
    "DLTR": "Dollar Tree Inc.",
    "ORLY": "O'Reilly Automotive Inc.",
    "AZO": "AutoZone Inc.",
    "AAP": "Advance Auto Parts Inc.",
    "BBY": "Best Buy Co. Inc.",
    "EBAY": "eBay Inc.",
    "ETSY": "Etsy Inc.",
    "W": "Wayfair Inc.",
    "BKNG": "Booking Holdings Inc.",
    "EXPE": "Expedia Group Inc.",
    "MAR": "Marriott International",
    "HLT": "Hilton Worldwide Holdings",
    "H": "Hyatt Hotels Corporation",
    "RCL": "Royal Caribbean Cruises",
    "CCL": "Carnival Corporation",
    "NCLH": "Norwegian Cruise Line",
    "LVS": "Las Vegas Sands Corp.",
    "MGM": "MGM Resorts International",
    "WYNN": "Wynn Resorts Limited",
    "F": "Ford Motor Company",
    "GM": "General Motors Company",
    "RIVN": "Rivian Automotive Inc.",
    "LCID": "Lucid Group Inc.",
    "NIO": "NIO Inc.",
    "LI": "Li Auto Inc.",
    "XPEV": "XPeng Inc.",
    
    # === CONSUMO DEFENSIVO ===
    "PM": "Philip Morris International",
    "MO": "Altria Group Inc.",
    "BTI": "British American Tobacco",
    "EL": "The Estée Lauder Companies",
    "CL": "Colgate-Palmolive Company",
    "KMB": "Kimberly-Clark Corporation",
    "CHD": "Church & Dwight Co. Inc.",
    "CLX": "The Clorox Company",
    "SJM": "The J.M. Smucker Company",
    "GIS": "General Mills Inc.",
    "K": "Kellogg Company",
    "MDLZ": "Mondelez International",
    "HSY": "The Hershey Company",
    "KHC": "The Kraft Heinz Company",
    "TSN": "Tyson Foods Inc.",
    "HRL": "Hormel Foods Corporation",
    "CAG": "Conagra Brands Inc.",
    "CPB": "Campbell Soup Company",
    "SYY": "Sysco Corporation",
    "KR": "The Kroger Co.",
    "ACI": "Albertsons Companies Inc.",
    
    # === ENERGÍA ===
    "COP": "ConocoPhillips",
    "EOG": "EOG Resources Inc.",
    "SLB": "Schlumberger Limited",
    "PXD": "Pioneer Natural Resources",
    "MPC": "Marathon Petroleum Corp.",
    "VLO": "Valero Energy Corporation",
    "PSX": "Phillips 66",
    "OXY": "Occidental Petroleum Corp.",
    "HES": "Hess Corporation",
    "DVN": "Devon Energy Corporation",
    "FANG": "Diamondback Energy Inc.",
    "HAL": "Halliburton Company",
    "BKR": "Baker Hughes Company",
    "KMI": "Kinder Morgan Inc.",
    "WMB": "The Williams Companies",
    "OKE": "ONEOK Inc.",
    "ET": "Energy Transfer LP",
    "EPD": "Enterprise Products Partners",
    "LNG": "Cheniere Energy Inc.",
    
    # === UTILITIES ===
    "DUK": "Duke Energy Corporation",
    "SO": "The Southern Company",
    "D": "Dominion Energy Inc.",
    "AEP": "American Electric Power",
    "EXC": "Exelon Corporation",
    "SRE": "Sempra",
    "XEL": "Xcel Energy Inc.",
    "ED": "Consolidated Edison Inc.",
    "WEC": "WEC Energy Group Inc.",
    "ES": "Eversource Energy",
    "AWK": "American Water Works Co.",
    "AEE": "Ameren Corporation",
    "CMS": "CMS Energy Corporation",
    "DTE": "DTE Energy Company",
    "PPL": "PPL Corporation",
    "FE": "FirstEnergy Corp.",
    "ETR": "Entergy Corporation",
    "PEG": "Public Service Enterprise",
    "EIX": "Edison International",
    "PCG": "PG&E Corporation",
    
    # === REAL ESTATE / REITs ===
    "AMT": "American Tower Corporation",
    "PLD": "Prologis Inc.",
    "CCI": "Crown Castle Inc.",
    "EQIX": "Equinix Inc.",
    "PSA": "Public Storage",
    "O": "Realty Income Corporation",
    "SPG": "Simon Property Group",
    "WELL": "Welltower Inc.",
    "DLR": "Digital Realty Trust",
    "AVB": "AvalonBay Communities",
    "EQR": "Equity Residential",
    "VTR": "Ventas Inc.",
    "ARE": "Alexandria Real Estate",
    "SBAC": "SBA Communications Corp.",
    "WY": "Weyerhaeuser Company",
    "CBRE": "CBRE Group Inc.",
    "MAA": "Mid-America Apartment",
    "UDR": "UDR Inc.",
    "ESS": "Essex Property Trust",
    "HST": "Host Hotels & Resorts",
    "PEAK": "Healthpeak Properties",
    "KIM": "Kimco Realty Corporation",
    "REG": "Regency Centers Corp.",
    "CPT": "Camden Property Trust",
    "EXR": "Extra Space Storage",
    "CUBE": "CubeSmart",
    "IRM": "Iron Mountain Inc.",
    
    # === INDUSTRIALES ===
    "CAT": "Caterpillar Inc.",
    "DE": "Deere & Company",
    "BA": "The Boeing Company",
    "HON": "Honeywell International",
    "UPS": "United Parcel Service",
    "UNP": "Union Pacific Corporation",
    "LMT": "Lockheed Martin Corporation",
    "NOC": "Northrop Grumman Corp.",
    "GD": "General Dynamics Corp.",
    "GE": "General Electric Company",
    "MMM": "3M Company",
    "ETN": "Eaton Corporation plc",
    "ITW": "Illinois Tool Works Inc.",
    "EMR": "Emerson Electric Co.",
    "PH": "Parker-Hannifin Corp.",
    "ROK": "Rockwell Automation",
    "CMI": "Cummins Inc.",
    "PCAR": "PACCAR Inc.",
    "DAL": "Delta Air Lines Inc.",
    "UAL": "United Airlines Holdings",
    "AAL": "American Airlines Group",
    "LUV": "Southwest Airlines Co.",
    "FDX": "FedEx Corporation",
    "NSC": "Norfolk Southern Corp.",
    "CSX": "CSX Corporation",
    "JBHT": "J.B. Hunt Transport",
    "ODFL": "Old Dominion Freight Line",
    "XPO": "XPO Inc.",
    "CHRW": "C.H. Robinson Worldwide",
    "EXPD": "Expeditors International",
    "WAB": "Westinghouse Air Brake",
    "TT": "Trane Technologies plc",
    "CARR": "Carrier Global Corp.",
    "OTIS": "Otis Worldwide Corporation",
    "JCI": "Johnson Controls Int'l",
    "FAST": "Fastenal Company",
    "URI": "United Rentals Inc.",
    "PWR": "Quanta Services Inc.",
    "IR": "Ingersoll Rand Inc.",
    "AME": "AMETEK Inc.",
    "ROP": "Roper Technologies Inc.",
    "IEX": "IDEX Corporation",
    "DOV": "Dover Corporation",
    "SWK": "Stanley Black & Decker",
    "GNRC": "Generac Holdings Inc.",
    
    # === MATERIALES ===
    "LIN": "Linde plc",
    "APD": "Air Products and Chemicals",
    "SHW": "The Sherwin-Williams Co.",
    "ECL": "Ecolab Inc.",
    "FCX": "Freeport-McMoRan Inc.",
    "NEM": "Newmont Corporation",
    "NUE": "Nucor Corporation",
    "STLD": "Steel Dynamics Inc.",
    "VMC": "Vulcan Materials Company",
    "MLM": "Martin Marietta Materials",
    "DOW": "Dow Inc.",
    "DD": "DuPont de Nemours Inc.",
    "PPG": "PPG Industries Inc.",
    "ALB": "Albemarle Corporation",
    "EMN": "Eastman Chemical Company",
    "CE": "Celanese Corporation",
    "CF": "CF Industries Holdings",
    "MOS": "The Mosaic Company",
    "FMC": "FMC Corporation",
    "CTVA": "Corteva Inc.",
    "IFF": "International Flavors",
    "BALL": "Ball Corporation",
    "PKG": "Packaging Corp of America",
    "IP": "International Paper Co.",
    "WRK": "WestRock Company",
    "AVY": "Avery Dennison Corp.",
    
    # === COMUNICACIONES ===
    "TMUS": "T-Mobile US Inc.",
    "CHTR": "Charter Communications",
    "ATVI": "Activision Blizzard",
    "EA": "Electronic Arts Inc.",
    "TTWO": "Take-Two Interactive",
    "RBLX": "Roblox Corporation",
    "WBD": "Warner Bros. Discovery",
    "PARA": "Paramount Global",
    "FOX": "Fox Corporation",
    "FOXA": "Fox Corporation Class A",
    "NWSA": "News Corporation",
    "OMC": "Omnicom Group Inc.",
    "IPG": "Interpublic Group",
    "LYV": "Live Nation Entertainment",
    "MTCH": "Match Group Inc.",
    "PINS": "Pinterest Inc.",
    "SNAP": "Snap Inc.",
    "TWTR": "Twitter Inc.",
    
    # === ETFs POPULARES ===
    "SPY": "SPDR S&P 500 ETF Trust",
    "QQQ": "Invesco QQQ Trust",
    "IWM": "iShares Russell 2000 ETF",
    "DIA": "SPDR Dow Jones Industrial",
    "VOO": "Vanguard S&P 500 ETF",
    "VTI": "Vanguard Total Stock Market",
    "VEA": "Vanguard FTSE Developed",
    "VWO": "Vanguard FTSE Emerging",
    "VNQ": "Vanguard Real Estate ETF",
    "BND": "Vanguard Total Bond Market",
    "AGG": "iShares Core US Aggregate",
    "GLD": "SPDR Gold Shares",
    "SLV": "iShares Silver Trust",
    "USO": "United States Oil Fund",
    "XLK": "Technology Select Sector",
    "XLF": "Financial Select Sector",
    "XLV": "Health Care Select Sector",
    "XLE": "Energy Select Sector",
    "XLY": "Consumer Discretionary",
    "XLP": "Consumer Staples Select",
    "XLI": "Industrial Select Sector",
    "XLB": "Materials Select Sector",
    "XLU": "Utilities Select Sector",
    "XLRE": "Real Estate Select Sector",
    "XLC": "Communication Services",
    "ARKK": "ARK Innovation ETF",
    "ARKW": "ARK Next Gen Internet",
    "ARKG": "ARK Genomic Revolution",
    "ARKF": "ARK Fintech Innovation",
    "VIG": "Vanguard Dividend Appreciation",
    "VYM": "Vanguard High Dividend Yield",
    "SCHD": "Schwab US Dividend Equity",
    "DVY": "iShares Select Dividend",
    "DGRO": "iShares Core Dividend Growth",
    "HDV": "iShares Core High Dividend",
    "NOBL": "ProShares S&P 500 Dividend",
    "TLT": "iShares 20+ Year Treasury",
    "IEF": "iShares 7-10 Year Treasury",
    "SHY": "iShares 1-3 Year Treasury",
    "LQD": "iShares iBoxx Investment Grade",
    "HYG": "iShares iBoxx High Yield",
    "EMB": "iShares JP Morgan USD EM Bond",
    "EFA": "iShares MSCI EAFE ETF",
    "EEM": "iShares MSCI Emerging Markets",
    "IEFA": "iShares Core MSCI EAFE",
    "IEMG": "iShares Core MSCI Emerging",
    
    # === INTERNACIONALES POPULARES ===
    "BABA": "Alibaba Group Holding",
    "JD": "JD.com Inc.",
    "PDD": "PDD Holdings Inc.",
    "BIDU": "Baidu Inc.",
    "TCEHY": "Tencent Holdings (OTC)",
    "TSM": "Taiwan Semiconductor",
    "ASML": "ASML Holding N.V.",
    "SAP": "SAP SE",
    "TM": "Toyota Motor Corporation",
    "SONY": "Sony Group Corporation",
    "NVS": "Novartis AG",
    "AZN": "AstraZeneca PLC",
    "GSK": "GSK plc",
    "SNY": "Sanofi",
    "SHEL": "Shell plc",
    "BP": "BP p.l.c.",
    "TTE": "TotalEnergies SE",
    "RIO": "Rio Tinto Group",
    "BHP": "BHP Group Limited",
    "VALE": "Vale S.A.",
    "UL": "Unilever PLC",
    "DEO": "Diageo plc",
    "BUD": "Anheuser-Busch InBev",
    "NVO": "Novo Nordisk A/S",
    "LLY": "Eli Lilly and Company",
    "HSBC": "HSBC Holdings plc",
    "UBS": "UBS Group AG",
    "CS": "Credit Suisse Group",
    "DB": "Deutsche Bank AG",
    "ING": "ING Groep N.V.",
    "BNPQY": "BNP Paribas (OTC)",
    "TD": "Toronto-Dominion Bank",
    "RY": "Royal Bank of Canada",
    "BMO": "Bank of Montreal",
    "BNS": "Bank of Nova Scotia",
    "CNI": "Canadian National Railway",
    "CP": "Canadian Pacific Kansas City",
    "ENB": "Enbridge Inc.",
    "TRP": "TC Energy Corporation",
    "SU": "Suncor Energy Inc.",
    "CNQ": "Canadian Natural Resources",
    
    # === CRIPTOMONEDAS RELACIONADAS ===
    "MSTR": "MicroStrategy Incorporated",
    "MARA": "Marathon Digital Holdings",
    "RIOT": "Riot Platforms Inc.",
    "HUT": "Hut 8 Mining Corp.",
    "BITF": "Bitfarms Ltd.",
    "CLSK": "CleanSpark Inc.",
    "CIFR": "Cipher Mining Inc.",
    "BTBT": "Bit Digital Inc.",
    "GBTC": "Grayscale Bitcoin Trust",
    "ETHE": "Grayscale Ethereum Trust",
    
    # === SPACS Y OTRAS ===
    "SOFI": "SoFi Technologies Inc.",
    "HOOD": "Robinhood Markets Inc.",
    "AFRM": "Affirm Holdings Inc.",
    "UPST": "Upstart Holdings Inc.",
    "LMND": "Lemonade Inc.",
    "ROOT": "Root Inc.",
    "OPEN": "Opendoor Technologies",
    "RDFN": "Redfin Corporation",
    "Z": "Zillow Group Inc.",
    "ZG": "Zillow Group Inc. Class A",
    "CVNA": "Carvana Co.",
    "VRM": "Vroom Inc.",
    "CHWY": "Chewy Inc.",
    "WOOF": "Petco Health and Wellness",
    "BARK": "BARK Inc.",
    "BYND": "Beyond Meat Inc.",
    "TTCF": "Tattooed Chef Inc.",
    "OATLY": "Oatly Group AB",
    "PATH": "UiPath Inc.",
    "AI": "C3.ai Inc.",
    "BBAI": "BigBear.ai Holdings",
    "SOUN": "SoundHound AI Inc.",
    "UPWK": "Upwork Inc.",
    "FVRR": "Fiverr International",
    "U": "Unity Software Inc.",
    "RBLX": "Roblox Corporation",
    "APP": "AppLovin Corporation",
    "TTD": "The Trade Desk Inc.",
    "PUBM": "PubMatic Inc.",
    "MGNI": "Magnite Inc.",
    "IS": "ironSource Ltd.",
    "DV": "DoubleVerify Holdings",
    "APPS": "Digital Turbine Inc.",
    "SKLZ": "Skillz Inc.",
    "DKNG": "DraftKings Inc.",
    "PENN": "Penn Entertainment Inc.",
    "GENI": "Genius Sports Limited",
    "RSI": "Rush Street Interactive",
    "EVRI": "Everi Holdings Inc.",
    "CHDN": "Churchill Downs Inc.",
    "FLUT": "Flutter Entertainment",
}


def search_stocks(query: str, limit: int = 10) -> list:
    """
    Busca acciones que coincidan con el query.
    Retorna lista de tuplas (ticker, nombre, match_score).
    """
    if not query or len(query) < 1:
        return []
    
    query_upper = query.upper().strip()
    query_lower = query.lower().strip()
    results = []
    
    for ticker, name in POPULAR_STOCKS.items():
        score = 0
        ticker_upper = ticker.upper()
        name_lower = name.lower()
        
        # Match exacto de ticker = máxima prioridad
        if ticker_upper == query_upper:
            score = 1000
        # Ticker empieza con query
        elif ticker_upper.startswith(query_upper):
            score = 500 + (100 - len(ticker))  # Tickers más cortos primero
        # Ticker contiene query
        elif query_upper in ticker_upper:
            score = 300
        # Nombre empieza con query
        elif name_lower.startswith(query_lower):
            score = 400
        # Alguna palabra del nombre empieza con query
        elif any(word.startswith(query_lower) for word in name_lower.split()):
            score = 200
        # Nombre contiene query
        elif query_lower in name_lower:
            score = 100
        
        if score > 0:
            results.append((ticker, name, score))
    
    # Ordenar por score (mayor primero) y luego alfabéticamente
    results.sort(key=lambda x: (-x[2], x[0]))
    
    return results[:limit]


def get_stock_display(ticker: str) -> str:
    """Retorna el nombre completo de un ticker."""
    return POPULAR_STOCKS.get(ticker.upper(), ticker)


def format_suggestion(ticker: str, name: str) -> str:
    """Formatea una sugerencia para mostrar."""
    return f"{ticker} - {name}"


# Lista rápida de los tickers más populares para mostrar por defecto
TOP_STOCKS = [
    "AAPL", "MSFT", "GOOGL", "AMZN", "NVDA", "META", "TSLA", "BRK-B",
    "JPM", "V", "JNJ", "UNH", "XOM", "MA", "PG", "HD", "CVX", "LLY",
    "MRK", "ABBV", "PEP", "KO", "COST", "MCD", "WMT", "CSCO", "NFLX",
    "AMD", "INTC", "DIS", "PFE", "BA", "CAT", "GS", "MS", "PYPL", "SQ"
]
